### PR TITLE
Added Herald logos

### PR DESCRIPTION
**Pull request by adamfowleruk**
Signed-off-by: Adam Fowler <adamfowleruk@gmail.com>

### CODE REVIEW

**Review by jennydove — COMMENTED** [review]
Looking at the preview, nothing seems to be rendering in the rich diff view. I am not sure why, though if I had to guess might be because of the spaces in the filenames? Any ideas?

**Comment by ryjones** [comment]
@jennydove I'm able to view the files in [Chrome](https://github.com/lfph/artwork/blob/08bc136aade021a648c9f1362697007ccb5375b9/projects/herald/stacked/gray/661330%20Herald%20OSS%20Logo%20Final%20Gray%20Stacked.svg) and Safari

**Comment by jennydove** [comment]
It looks like this for me: 

image

But if you say that it works for you, then I'll assume it's just something strange about my machine and i'm happy to see it merged.

**Comment by ryjones** [comment]
64122888-B484-4FFD-8065-C01EF4832DDF is what I see

**Pull request merged**
