### PR TITLE
add horizontal web logos

### PR DESCRIPTION
**Pull request by alexcontini**

### CODE REVIEW

**Comment by cjyabraham** [comment]
The SVG horizontal-long image is actually a PNG.  Can you replace it with an SVG please?

**Comment by alexcontini** [comment]
@cjyabraham I checked and there is a svg in each folder, ie. https://github.com/lfph/artwork/blob/contini-add-horizontal-logos/lfph/horizontal-long/color/lfph-horizontal-long-color.svg (I opened it and the files seems to be correct), I might have misunderstood thought so let me know!

**Comment by cjyabraham** [comment]
The SVG just wasn't linked in properly in the README.  [I've fixed it here](https://github.com/lfph/artwork/commit/e64049ec82609d6217b9c02399554be8c7848242).

**Comment by alexcontini** [comment]
going to close this PR as there is a new one here - https://github.com/lfph/artwork/pull/3

**Pull request closed without merging**
